name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  all:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Windows, Ubuntu, MacOS]

    steps:
    - uses: actions/checkout@v1

    # Cache pre-commit
    - name: for pre-commit caching
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" > $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pipx run nox
